package icu.nullptr.polyglot.settings

import icu.nullptr.polyglot.R
import icu.nullptr.polyglot.core.ConfigManager
import icu.nullptr.polyglot.module

object SettingsOptions {

    val providers = listOf(
        SettingsOption(ConfigManager.PROVIDER_GOOGLE, "Google Translate"),
        SettingsOption(ConfigManager.PROVIDER_MICROSOFT, "Microsoft Translator"),
        SettingsOption(ConfigManager.PROVIDER_OPENAI, "OpenAI compatible"),
    )

    val targetLanguages = listOf(
        SettingsOption("ab", "Abkhaz"),
        SettingsOption("ace", "Acehnese"),
        SettingsOption("ach", "Acholi"),
        SettingsOption("aa", "Afar"),
        SettingsOption("af", "Afrikaans"),
        SettingsOption("sq", "Albanian"),
        SettingsOption("alz", "Alur"),
        SettingsOption("am", "Amharic"),
        SettingsOption("ar", "Arabic"),
        SettingsOption("hy", "Armenian"),
        SettingsOption("as", "Assamese"),
        SettingsOption("av", "Avar"),
        SettingsOption("awa", "Awadhi"),
        SettingsOption("ay", "Aymara"),
        SettingsOption("az", "Azerbaijani"),
        SettingsOption("ban", "Balinese"),
        SettingsOption("bal", "Baluchi"),
        SettingsOption("bm", "Bambara"),
        SettingsOption("bci", "Baoulé"),
        SettingsOption("ba", "Bashkir"),
        SettingsOption("eu", "Basque"),
        SettingsOption("btx", "Batak Karo"),
        SettingsOption("bts", "Batak Simalungun"),
        SettingsOption("bbc", "Batak Toba"),
        SettingsOption("be", "Belarusian"),
        SettingsOption("bem", "Bemba"),
        SettingsOption("bn", "Bengali"),
        SettingsOption("bew", "Betawi"),
        SettingsOption("bho", "Bhojpuri"),
        SettingsOption("bik", "Bikol"),
        SettingsOption("bs", "Bosnian"),
        SettingsOption("br", "Breton"),
        SettingsOption("bg", "Bulgarian"),
        SettingsOption("bua", "Buryat"),
        SettingsOption("yue", "Cantonese"),
        SettingsOption("ca", "Catalan"),
        SettingsOption("ceb", "Cebuano"),
        SettingsOption("ch", "Chamorro"),
        SettingsOption("ce", "Chechen"),
        SettingsOption("ny", "Chichewa"),
        SettingsOption("zh-CN", "Chinese (Simplified)"),
        SettingsOption("zh-TW", "Chinese (Traditional)"),
        SettingsOption("chk", "Chuukese"),
        SettingsOption("cv", "Chuvash"),
        SettingsOption("co", "Corsican"),
        SettingsOption("crh-Cyrl", "Crimean Tatar (Cyrillic)"),
        SettingsOption("crh-Latn", "Crimean Tatar (Latin)"),
        SettingsOption("hr", "Croatian"),
        SettingsOption("cs", "Czech"),
        SettingsOption("da", "Danish"),
        SettingsOption("prs", "Dari"),
        SettingsOption("dv", "Dhivehi"),
        SettingsOption("din", "Dinka"),
        SettingsOption("doi", "Dogri"),
        SettingsOption("kvy", "Dombe"),
        SettingsOption("nl", "Dutch"),
        SettingsOption("dyu", "Dyula"),
        SettingsOption("dz", "Dzongkha"),
        SettingsOption("en", "English"),
        SettingsOption("eo", "Esperanto"),
        SettingsOption("et", "Estonian"),
        SettingsOption("ee", "Ewe"),
        SettingsOption("fo", "Faroese"),
        SettingsOption("fj", "Fijian"),
        SettingsOption("tl", "Filipino"),
        SettingsOption("fi", "Finnish"),
        SettingsOption("fon", "Fon"),
        SettingsOption("fr", "French"),
        SettingsOption("fr-CA", "French (Canada)"),
        SettingsOption("fy", "Frisian"),
        SettingsOption("fur", "Friulian"),
        SettingsOption("ff", "Fulani"),
        SettingsOption("gaa", "Ga"),
        SettingsOption("gl", "Galician"),
        SettingsOption("ka", "Georgian"),
        SettingsOption("de", "German"),
        SettingsOption("el", "Greek"),
        SettingsOption("gn", "Guarani"),
        SettingsOption("gu", "Gujarati"),
        SettingsOption("ht", "Haitian Creole"),
        SettingsOption("cnh", "Hakha Chin"),
        SettingsOption("ha", "Hausa"),
        SettingsOption("haw", "Hawaiian"),
        SettingsOption("he", "Hebrew"),
        SettingsOption("hil", "Hiligaynon"),
        SettingsOption("hi", "Hindi"),
        SettingsOption("hmn", "Hmong"),
        SettingsOption("hu", "Hungarian"),
        SettingsOption("hrx", "Hunsrik"),
        SettingsOption("iba", "Iban"),
        SettingsOption("is", "Icelandic"),
        SettingsOption("ig", "Igbo"),
        SettingsOption("ilo", "Ilocano"),
        SettingsOption("id", "Indonesian"),
        SettingsOption("iu-Latn", "Inuktut (Latin)"),
        SettingsOption("iu", "Inuktut (Syllabics)"),
        SettingsOption("ga", "Irish"),
        SettingsOption("it", "Italian"),
        SettingsOption("jam", "Jamaican Patois"),
        SettingsOption("ja", "Japanese"),
        SettingsOption("jv", "Javanese"),
        SettingsOption("kac", "Jingpo"),
        SettingsOption("kl", "Kalaallisut"),
        SettingsOption("kn", "Kannada"),
        SettingsOption("kr", "Kanuri"),
        SettingsOption("pam", "Kapampangan"),
        SettingsOption("kk", "Kazakh"),
        SettingsOption("kha", "Khasi"),
        SettingsOption("km", "Khmer"),
        SettingsOption("cgg", "Kiga"),
        SettingsOption("kg", "Kikongo"),
        SettingsOption("rw", "Kinyarwanda"),
        SettingsOption("ktu", "Kituba"),
        SettingsOption("trp", "Kokborok"),
        SettingsOption("kv", "Komi"),
        SettingsOption("gom", "Konkani"),
        SettingsOption("ko", "Korean"),
        SettingsOption("kri", "Krio"),
        SettingsOption("kmr", "Kurdish (Kurmanji)"),
        SettingsOption("ckb", "Kurdish (Sorani)"),
        SettingsOption("ky", "Kyrgyz"),
        SettingsOption("lo", "Lao"),
        SettingsOption("ltg", "Latgalian"),
        SettingsOption("la", "Latin"),
        SettingsOption("lv", "Latvian"),
        SettingsOption("lij", "Ligurian"),
        SettingsOption("li", "Limburgish"),
        SettingsOption("ln", "Lingala"),
        SettingsOption("lt", "Lithuanian"),
        SettingsOption("lmo", "Lombard"),
        SettingsOption("lg", "Luganda"),
        SettingsOption("luo", "Luo"),
        SettingsOption("lb", "Luxembourgish"),
        SettingsOption("mk", "Macedonian"),
        SettingsOption("mad", "Madurese"),
        SettingsOption("mai", "Maithili"),
        SettingsOption("mak", "Makassar"),
        SettingsOption("mg", "Malagasy"),
        SettingsOption("ms", "Malay"),
        SettingsOption("ms-Arab", "Malay (Jawi)"),
        SettingsOption("ml", "Malayalam"),
        SettingsOption("mt", "Maltese"),
        SettingsOption("mam", "Mam"),
        SettingsOption("gv", "Manx"),
        SettingsOption("mi", "Maori"),
        SettingsOption("mr", "Marathi"),
        SettingsOption("mh", "Marshallese"),
        SettingsOption("mwr", "Marwadi"),
        SettingsOption("mfe", "Mauritian Creole"),
        SettingsOption("mhr", "Meadow Mari"),
        SettingsOption("mni", "Meiteilon (Manipuri)"),
        SettingsOption("min", "Minang"),
        SettingsOption("lus", "Mizo"),
        SettingsOption("mn", "Mongolian"),
        SettingsOption("my", "Myanmar (Burmese)"),
        SettingsOption("nhe", "Nahuatl (Eastern Huasteca)"),
        SettingsOption("ndc", "Ndau"),
        SettingsOption("nr", "Ndebele (South)"),
        SettingsOption("new", "Nepalbhasa (Newari)"),
        SettingsOption("ne", "Nepali"),
        SettingsOption("nqo", "NKo"),
        SettingsOption("nb", "Norwegian (Bokmål)"),
        SettingsOption("nus", "Nuer"),
        SettingsOption("oc", "Occitan"),
        SettingsOption("or", "Odia (Oriya)"),
        SettingsOption("om", "Oromo"),
        SettingsOption("os", "Ossetian"),
        SettingsOption("pag", "Pangasinan"),
        SettingsOption("pap", "Papiamento"),
        SettingsOption("ps", "Pashto"),
        SettingsOption("fa", "Persian"),
        SettingsOption("pl", "Polish"),
        SettingsOption("pt-BR", "Portuguese (Brazil)"),
        SettingsOption("pt-PT", "Portuguese (Portugal)"),
        SettingsOption("pa", "Punjabi (Gurmukhi)"),
        SettingsOption("pa-Arab", "Punjabi (Shahmukhi)"),
        SettingsOption("qu", "Quechua"),
        SettingsOption("kek", "Qʼeqchiʼ"),
        SettingsOption("rom", "Romani"),
        SettingsOption("ro", "Romanian"),
        SettingsOption("rn", "Rundi"),
        SettingsOption("ru", "Russian"),
        SettingsOption("se", "Sami (North)"),
        SettingsOption("sm", "Samoan"),
        SettingsOption("sg", "Sango"),
        SettingsOption("sa", "Sanskrit"),
        SettingsOption("sat-Latn", "Santali (Latin)"),
        SettingsOption("sat", "Santali (Ol Chiki)"),
        SettingsOption("gd", "Scots Gaelic"),
        SettingsOption("nso", "Sepedi"),
        SettingsOption("sr", "Serbian"),
        SettingsOption("st", "Sesotho"),
        SettingsOption("crs", "Seychellois Creole"),
        SettingsOption("shn", "Shan"),
        SettingsOption("sn", "Shona"),
        SettingsOption("scn", "Sicilian"),
        SettingsOption("szl", "Silesian"),
        SettingsOption("sd", "Sindhi"),
        SettingsOption("si", "Sinhala"),
        SettingsOption("sk", "Slovak"),
        SettingsOption("sl", "Slovenian"),
        SettingsOption("so", "Somali"),
        SettingsOption("es", "Spanish"),
        SettingsOption("su", "Sundanese"),
        SettingsOption("sus", "Susu"),
        SettingsOption("sw", "Swahili"),
        SettingsOption("ss", "Swati"),
        SettingsOption("sv", "Swedish"),
        SettingsOption("ty", "Tahitian"),
        SettingsOption("tg", "Tajik"),
        SettingsOption("tzm", "Tamazight"),
        SettingsOption("zgh", "Tamazight (Tifinagh)"),
        SettingsOption("ta", "Tamil"),
        SettingsOption("tt", "Tatar"),
        SettingsOption("te", "Telugu"),
        SettingsOption("tet", "Tetum"),
        SettingsOption("th", "Thai"),
        SettingsOption("bo", "Tibetan"),
        SettingsOption("ti", "Tigrinya"),
        SettingsOption("tiv", "Tiv"),
        SettingsOption("tpi", "Tok Pisin"),
        SettingsOption("to", "Tongan"),
        SettingsOption("lu", "Tshiluba"),
        SettingsOption("ts", "Tsonga"),
        SettingsOption("tn", "Tswana"),
        SettingsOption("tcy", "Tulu"),
        SettingsOption("tum", "Tumbuka"),
        SettingsOption("tr", "Turkish"),
        SettingsOption("tk", "Turkmen"),
        SettingsOption("tyv", "Tuvan"),
        SettingsOption("ak", "Twi"),
        SettingsOption("udm", "Udmurt"),
        SettingsOption("uk", "Ukrainian"),
        SettingsOption("ur", "Urdu"),
        SettingsOption("ug", "Uyghur"),
        SettingsOption("uz", "Uzbek"),
        SettingsOption("ve", "Venda"),
        SettingsOption("vec", "Venetian"),
        SettingsOption("vi", "Vietnamese"),
        SettingsOption("war", "Waray"),
        SettingsOption("cy", "Welsh"),
        SettingsOption("wo", "Wolof"),
        SettingsOption("xh", "Xhosa"),
        SettingsOption("sah", "Yakut"),
        SettingsOption("yi", "Yiddish"),
        SettingsOption("yo", "Yoruba"),
        SettingsOption("yua", "Yucatec Maya"),
        SettingsOption("zap", "Zapotec"),
        SettingsOption("zu", "Zulu")
    )

    val subtitleMode = listOf(
        SettingsOption(ConfigManager.SUBTITLE_ORIGINAL_FIRST, module.res.getString(R.string.subtitle_mode_original_first)),
        SettingsOption(ConfigManager.SUBTITLE_TRANSLATION_FIRST, module.res.getString(R.string.subtitle_mode_translation_first)),
        SettingsOption(ConfigManager.SUBTITLE_TRANSLATION_ONLY, module.res.getString(R.string.subtitle_mode_translation_only))
    )

    fun enabledSummary(enabled: Boolean): String =
        if (enabled) module.res.getString(R.string.enabled)
        else module.res.getString(R.string.disabled)

    fun providerLabel(value: String): String =
        providers.firstOrNull { it.value == value }?.label ?: value

    fun languageLabel(value: String): String =
        targetLanguages.firstOrNull { it.value == value }?.label ?: value

    fun subtitleModeLabel(value: String): String =
        subtitleMode.firstOrNull { it.value == value }?.label ?: value

    fun textOrNotSet(value: String): String =
        value.ifBlank { module.res.getString(R.string.not_set) }

    fun secretSummary(value: String): String =
        if (value.isBlank()) module.res.getString(R.string.not_set) else "********"
}

data class SettingsOption(
    val value: String,
    val label: String,
)
